site_name: My Docs

repo_url: https://github.com/CreditMutuelArkea/tock

theme:
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
  name: material
  palette:
    primary: blue
  features:
    - content.action.edit
    - content.code.copy
    - navigation.expand
    - navigation.path

nav:
  # Ajoutez votre navigation ici

plugins:
  - git-authors
  - git-committers:
      repository: https://github.com/CreditMutuelArkea/tock
      branch: main
      
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Tock Documentation"
        - locale: fr
          name: Français
          build: true
          site_name: "Tock Documentation"
          theme:
            palette:
              primary: blue
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
